/**
 * Reward Function for RL Training
 * 
 * Calculates reward by comparing agent-generated workspace with target example
 */

import type { WorkspaceSnapshot } from '@maya/workspace-domain/workspace/core';
import type { TrainingExample } from './types';
import {
    compareShapeCounts,
    compareShapeTypes,
    computePositionSimilarity,
    computeDimensionSimilarity,
    checkConstraints,
} from './metrics';
import { classifyAction, ActionCategory } from './training/actionMapping';

export interface RewardBreakdown {
    shapeCount: number;
    shapeTypes: number;
    positions: number;
    dimensions: number;
}

export interface RewardResult {
    total: number;          // Combined reward 0-1
    shapeMatch: number;     // Shape matching component 0-1
    constraints: number;    // Constraint satisfaction 0-1
    breakdown: RewardBreakdown;
}

/**
 * Calculate reward for a generated workspace compared to target
 * 
 * @param generated - The workspace snapshot generated by the agent
 * @param target - The training example with target workspace
 * @param previousState - The state before this action (for comparison)
 * @param actionIndex - The action that was taken (for category-based penalties)
 * @returns Reward result with total score and breakdown
 */
export function calculateReward(
    generated: WorkspaceSnapshot,
    target: TrainingExample,
    previousState?: WorkspaceSnapshot,
    actionIndex?: number
): RewardResult {
    const targetSnapshot = target.targetSnapshot;

    // 1. Shape count similarity (0-0.2)
    const shapeCountScore = compareShapeCounts(generated, targetSnapshot) * 0.2;

    // 2. Shape type matching (0-0.3)
    const shapeTypeScore = compareShapeTypes(generated, targetSnapshot) * 0.3;

    // 3. Position similarity (0-0.25)
    let positionScore = 0;
    if (targetSnapshot.shapes.length > 0 && generated.shapes.length > 0) {
        // Calculate centroids to align the drawings
        const targetCenter = getSnapshotCentroid(targetSnapshot);
        const genCenter = getSnapshotCentroid(generated);
        const offsetX = targetCenter.x - genCenter.x;
        const offsetY = targetCenter.y - genCenter.y;

        // Match shapes and compute average position similarity
        let totalPosSim = 0;
        let matches = 0;

        for (const targetShape of targetSnapshot.shapes) {
            // Find best matching generated shape (same type)
            const candidates = generated.shapes.filter(s => s.type === targetShape.type);
            if (candidates.length > 0) {
                const bestMatch = candidates.reduce((best, candidate) => {
                    // Apply offset to candidate for comparison
                    const shiftedCandidate = shiftShape(candidate, offsetX, offsetY);
                    const sim = computePositionSimilarity(shiftedCandidate, targetShape);

                    // Also compare with best so far (shifted)
                    const shiftedBest = shiftShape(best, offsetX, offsetY);
                    const bestSim = computePositionSimilarity(shiftedBest, targetShape);

                    return sim > bestSim ? candidate : best;
                });

                const shiftedBestMatch = shiftShape(bestMatch, offsetX, offsetY);
                totalPosSim += computePositionSimilarity(shiftedBestMatch, targetShape);
                matches++;
            }
        }

        positionScore = matches > 0 ? (totalPosSim / matches) * 0.25 : 0;
    }

    // 4. Dimension similarity (0-0.25)
    let dimensionScore = 0;
    if (targetSnapshot.shapes.length > 0 && generated.shapes.length > 0) {
        let totalDimSim = 0;
        let matches = 0;

        for (const targetShape of targetSnapshot.shapes) {
            const candidates = generated.shapes.filter(s => s.type === targetShape.type);
            if (candidates.length > 0) {
                const bestMatch = candidates.reduce((best, candidate) => {
                    const sim = computeDimensionSimilarity(candidate, targetShape);
                    return sim > computeDimensionSimilarity(best, targetShape) ? candidate : best;
                });
                totalDimSim += computeDimensionSimilarity(bestMatch, targetShape);
                matches++;
            }
        }

        dimensionScore = matches > 0 ? (totalDimSim / matches) * 0.25 : 0;
    }

    // Total shape matching score (0-1)
    const shapeMatch = shapeCountScore + shapeTypeScore + positionScore + dimensionScore;

    // 5. Constraint satisfaction (0-1)
    const constraintsScore = checkConstraints(generated, target.constraints);

    // === NEW: Action-based penalties and bonuses ===
    let actionPenalty = 0;
    let actionBonus = 0;

    if (actionIndex !== undefined && previousState) {
        const category = classifyAction(actionIndex);
        const prevShapeCount = previousState.shapes.length;
        const newShapeCount = generated.shapes.length;

        // PENALTY: Utility actions on empty canvas (gentle nudge, not harsh punishment)
        if (category === ActionCategory.UTILITY && prevShapeCount === 0) {
            actionPenalty += 0.1;
        }

        // PENALTY: Transformation actions on empty canvas
        if (category === ActionCategory.TRANSFORMATION && prevShapeCount === 0) {
            actionPenalty += 0.05;
        }

        // BONUS: Creative actions that successfully add shapes (strong incentive!)
        if (category === ActionCategory.CREATIVE && newShapeCount > prevShapeCount) {
            actionBonus += 2.0;
        }

        // PENALTY: Creative actions that fail to add shapes (small discouragement)
        if (category === ActionCategory.CREATIVE && newShapeCount === prevShapeCount) {
            actionPenalty += 0.05;
        }
    }

    // Combined total (average of shape matching and constraints, adjusted by action bonuses/penalties)
    const baseReward = (shapeMatch + constraintsScore) / 2;
    const total = Math.max(-2.0, Math.min(3.0, baseReward + actionBonus - actionPenalty));

    return {
        total,
        shapeMatch,
        constraints: constraintsScore,
        breakdown: {
            shapeCount: shapeCountScore / 0.2,  // Normalize back to 0-1
            shapeTypes: shapeTypeScore / 0.3,
            positions: positionScore / 0.25,
            dimensions: dimensionScore / 0.25,
        },
    };
}

/**
 * Calculate reward and provide detailed explanation
 * Useful for debugging and understanding agent performance
 */
export function calculateRewardWithExplanation(
    generated: WorkspaceSnapshot,
    target: TrainingExample
): { reward: RewardResult; explanation: string } {
    const reward = calculateReward(generated, target);

    const lines = [
        `Reward Breakdown for: "${target.prompt}"`,
        ``,
        `Total Reward: ${reward.total.toFixed(3)}`,
        ``,
        `Shape Matching: ${reward.shapeMatch.toFixed(3)}`,
        `  - Shape Count: ${reward.breakdown.shapeCount.toFixed(3)} (target: ${target.targetSnapshot.shapes.length}, got: ${generated.shapes.length})`,
        `  - Shape Types: ${reward.breakdown.shapeTypes.toFixed(3)}`,
        `  - Positions: ${reward.breakdown.positions.toFixed(3)}`,
        `  - Dimensions: ${reward.breakdown.dimensions.toFixed(3)}`,
        ``,
        `Constraints: ${reward.constraints.toFixed(3)}`,
    ];

    if (target.constraints.dimensions) {
        lines.push(`  - Expected dimensions: ${target.constraints.dimensions.width.toFixed(2)}m x ${target.constraints.dimensions.height.toFixed(2)}m`);
    }
    if (target.constraints.roomCount) {
        lines.push(`  - Expected rooms: ${target.constraints.roomCount}`);
    }
    if (target.constraints.features && target.constraints.features.length > 0) {
        lines.push(`  - Required features: ${target.constraints.features.join(', ')}`);
    }

    return {
        reward,
        explanation: lines.join('\n'),
    };
}

// --- Helper Functions ---

function getSnapshotCentroid(snapshot: WorkspaceSnapshot): { x: number; y: number } {
    if (snapshot.shapes.length === 0) return { x: 0, y: 0 };

    let sumX = 0;
    let sumY = 0;
    let count = 0;

    snapshot.shapes.forEach(shape => {
        const center = getShapeCenter(shape);
        sumX += center.x;
        sumY += center.y;
        count++;
    });

    return { x: sumX / count, y: sumY / count };
}

function getShapeCenter(shape: any): { x: number; y: number } {
    // Simplified center calculation
    if (shape.start && shape.end) {
        return {
            x: (shape.start.x + shape.end.x) / 2,
            y: (shape.start.y + shape.end.y) / 2,
        };
    }
    if (shape.center) return shape.center;
    if (shape.centroid) return shape.centroid;
    if (shape.points) {
        const sumX = shape.points.reduce((s: number, p: any) => s + p.x, 0);
        const sumY = shape.points.reduce((s: number, p: any) => s + p.y, 0);
        return { x: sumX / shape.points.length, y: sumY / shape.points.length };
    }
    if (shape.centerline) {
        const cl = shape.centerline;
        return {
            x: (cl[0].x + cl[cl.length - 1].x) / 2,
            y: (cl[0].y + cl[cl.length - 1].y) / 2,
        };
    }
    return { x: 0, y: 0 };
}

function shiftShape(shape: any, dx: number, dy: number): any {
    const shifted = JSON.parse(JSON.stringify(shape)); // Deep clone

    if (shifted.start) { shifted.start.x += dx; shifted.start.y += dy; }
    if (shifted.end) { shifted.end.x += dx; shifted.end.y += dy; }
    if (shifted.center) { shifted.center.x += dx; shifted.center.y += dy; }
    if (shifted.centroid) { shifted.centroid.x += dx; shifted.centroid.y += dy; }
    if (shifted.points) {
        shifted.points.forEach((p: any) => { p.x += dx; p.y += dy; });
    }
    if (shifted.centerline) {
        shifted.centerline.forEach((p: any) => { p.x += dx; p.y += dy; });
    }
    return shifted;
}
